-- =============================================================================
-- MONITOR SLIDES
-- Menyimpan metadata gambar monitor agar dapat dibaca lintas perangkat.
-- Jalankan file ini satu kali melalui Supabase SQL Editor.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.monitor_slides (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  image_url text NOT NULL,
  storage_path text NULL,
  sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS monitor_slides_sort_order_idx
  ON public.monitor_slides (sort_order, created_at);

ALTER TABLE public.monitor_slides ENABLE ROW LEVEL SECURITY;

-- Hanya admin/super admin pada tabel pengguna aplikasi yang dapat mengelola slide.
CREATE OR REPLACE FUNCTION public.can_manage_monitor_slides()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    EXISTS (
      SELECT 1
      FROM public."Teknisi" AS teknisi
      JOIN public.roles AS user_role ON user_role.id = teknisi.roles_id
      WHERE teknisi.auth_id = auth.uid()
        AND lower(user_role.role) IN ('admin', 'super admin')
    )
    OR EXISTS (
      SELECT 1
      FROM public.dosen
      JOIN public.roles AS user_role ON user_role.id = dosen.roles_id
      WHERE dosen.auth_id = auth.uid()
        AND lower(user_role.role) IN ('admin', 'super admin')
    );
$$;

REVOKE ALL ON FUNCTION public.can_manage_monitor_slides() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.can_manage_monitor_slides() TO authenticated;

DROP POLICY IF EXISTS "Slide monitor aktif dapat dibaca publik"
  ON public.monitor_slides;
CREATE POLICY "Slide monitor aktif dapat dibaca publik"
  ON public.monitor_slides
  FOR SELECT
  TO anon, authenticated
  USING (is_active);

DROP POLICY IF EXISTS "Admin dapat membaca semua monitor slides"
  ON public.monitor_slides;
CREATE POLICY "Admin dapat membaca semua monitor slides"
  ON public.monitor_slides
  FOR SELECT
  TO authenticated
  USING (public.can_manage_monitor_slides());

DROP POLICY IF EXISTS "Admin dapat menambah monitor slides"
  ON public.monitor_slides;
CREATE POLICY "Admin dapat menambah monitor slides"
  ON public.monitor_slides
  FOR INSERT
  TO authenticated
  WITH CHECK (public.can_manage_monitor_slides());

DROP POLICY IF EXISTS "Admin dapat mengubah monitor slides"
  ON public.monitor_slides;
CREATE POLICY "Admin dapat mengubah monitor slides"
  ON public.monitor_slides
  FOR UPDATE
  TO authenticated
  USING (public.can_manage_monitor_slides())
  WITH CHECK (public.can_manage_monitor_slides());

DROP POLICY IF EXISTS "Admin dapat menghapus monitor slides"
  ON public.monitor_slides;
CREATE POLICY "Admin dapat menghapus monitor slides"
  ON public.monitor_slides
  FOR DELETE
  TO authenticated
  USING (public.can_manage_monitor_slides());

GRANT SELECT ON public.monitor_slides TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.monitor_slides TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.monitor_slides_id_seq TO authenticated;

-- Bucket khusus yang publik hanya untuk file gambar monitor.
INSERT INTO storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
VALUES (
  'monitor-slides',
  'monitor-slides',
  true,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "Admin dapat upload gambar monitor"
  ON storage.objects;
CREATE POLICY "Admin dapat upload gambar monitor"
  ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'monitor-slides'
    AND public.can_manage_monitor_slides()
  );

DROP POLICY IF EXISTS "Admin dapat membaca file gambar monitor"
  ON storage.objects;
CREATE POLICY "Admin dapat membaca file gambar monitor"
  ON storage.objects
  FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'monitor-slides'
    AND public.can_manage_monitor_slides()
  );

DROP POLICY IF EXISTS "Admin dapat mengubah gambar monitor"
  ON storage.objects;
CREATE POLICY "Admin dapat mengubah gambar monitor"
  ON storage.objects
  FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'monitor-slides'
    AND public.can_manage_monitor_slides()
  )
  WITH CHECK (
    bucket_id = 'monitor-slides'
    AND public.can_manage_monitor_slides()
  );

DROP POLICY IF EXISTS "Admin dapat menghapus gambar monitor"
  ON storage.objects;
CREATE POLICY "Admin dapat menghapus gambar monitor"
  ON storage.objects
  FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'monitor-slides'
    AND public.can_manage_monitor_slides()
  );

-- Aktifkan perubahan realtime agar TV menerima gambar baru tanpa reload.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'monitor_slides'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.monitor_slides;
  END IF;
END
$$;
